server:
  port: 9013

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  cloud:
    gcp:
      project-id: firstcoloudpubsu-1641885915064